### ISSUE TITLE
There are have datas in the console, But it can't show in the html?

### ISSUE THREAD

**Issue by TrevorYS** [posva/vue-promised#117]
![image](https://user-images.githubusercontent.com/19200800/71608899-58fdd700-2bbf-11ea-9e37-d0a93ba4029c.png)
![image](https://user-images.githubusercontent.com/19200800/71608918-6b781080-2bbf-11ea-83ad-756e762c6f77.png)
![image](https://user-images.githubusercontent.com/19200800/71608924-759a0f00-2bbf-11ea-9383-155689a31d07.png)

what wrong with me?

**Comment by posva** [comment]
You need to remove `list` from `data` and make sure you return the list in the `then`:

```js
this.eventList = analyze.eventList({}).then(res => {
  console.log('res)
  return res
})
```
