### ISSUE TITLE
[Feature] CDN mode

### ISSUE THREAD

**Issue by ibrahimBeladi** [posva/vue-promised#131]
Is it possible to have vue-promised as cdn?

**Comment by ibrahimBeladi** [comment]
This is what I ended up:
Include the cdn link
`<script src="https://cdn.jsdelivr.net/npm/vue-promised@1.2.2/dist/vue-promised.min.js"></script>`
Then register it as Vue component
`Vue.component("vue-promised", VuePromised.Promised);`

This should close my issue; if you have any more information, or recommendations please comment.

**Comment by posva** [comment]
as you figured out, the answer is yes :)
