### ISSUE TITLE
Pass a callback by props to be called after the promise is resolved

### ISSUE THREAD

**Issue by nicolidin** [posva/vue-promised#161]
Hey, 

I wrote a component similar to this one (I did not know this component already existed) with almost the same spec, but I had an **extra** props: `callBack` that I called in the implementation of my `Promise` component after the `promise` (passed by props) is resolved.

It's an essential feature I think because almost every time we call a promise we want to call another method after the promise is resolved.

What do you think about this new proposal feature ? 
If you want I can develop this feature and do a Pr?

**Comment by posva** [comment]
Hi, thank you for the proposal but I don't think this needs a new api

> It's an essential feature I think because almost every time we call a promise we want to call another method after the promise is resolved.

I would just append a `then` to the initial promise when setting it:

```js
this.promise = fetchData().then(data => {
  // do stuff
  return data
})
```

or keep the original promise but do a different `then`

```js
this.promise = fetchData()
this.promise.then(() => {
  // do stuff
})
```
