### ISSUE TITLE
Compatibility with vue 2.6.x

### ISSUE THREAD

**Issue by ibes** [posva/vue-promised#18]
Hi there,

I tried to follow the tutorial of vue-dose to slots in new vue 2.6.x format.
I am very new to slots so likely I get things wrong - but can it be that vue-promised is not yet compatible with vue 2.6.x slots?

Link to the tutorial: 
https://vuedose.tips/tips/4

**Comment by ibes** [comment]
then the problem lays on my side. Good to know.

**Comment by posva** [comment]
I updated the examples with the new syntax :)

**Comment by ibes** [comment]
Thank you.

The example without "combined" is still not using the new v-slot, right?
Is that not possible?

Sorry - I really have to little knowledge about it - I just try to understand how it is done and try to find out, if the vuedose.tips solution should be usable or if there is a error in what the author wrote. 
So for me right now it is to try to understand patterns.

**Comment by Trif4** [comment]
I can't get it to work with the new syntax either. `<template slot="pending">` works, but `<template #pending>` doesn't.

**Comment by ibes** [comment]
As far as I get it `slot` has just similarities but is not the same as `v-slot` (<- the new thing)
and `#pending` is a shothand for `v-slot=pending`

I was not able to get v-promised to work with the new v-slot syntax.

I already asked the author of vuedose if he can help to clarify things. 

Maybe his code example was just a "would look like" and not a "this actually work"

**Comment by Trif4** [comment]
This is due to [this issue](https://github.com/vuejs/vue/issues/9458) which is resolved in Vue 2.6.4.

**Comment by ibes** [comment]
Could you please share a working example of using vue-promised with the 2.6.x syntax that works for you @Trif4 ?

**Comment by ibes** [comment]
@posva - doesn't yet feel solved/closed.
But likely is not something that needs to be fixed in vue-promised put feels like there is some documentation that could be helpful for vue 2.6.x and newer

**Comment by posva** [comment]
The syntax is working correctly, the readme is up to date, the demos are using the new syntax and I checked vuedose and the example is good too...
The reverse proxy deployed on now is failing but maybe it is because they updated their platform. I will have to deploy another reverse proxy or an api to retrieve the xkcd comics

**Comment by ibes** [comment]
thank you for verifying :)
