### ISSUE TITLE
Bug: Only first slot element is shown

### ISSUE THREAD

**Issue by bodograumann** [posva/vue-promised#22]
It seems that when multiple children are passed to the combined slot, only the first one is displayed.

I first thought that maybe it is because it tries to nest my `<div>`s inside a `<span>`, but setting `v-bind:tag` to `div` also did not help.

```typescript
<Promised :promise="promise" :tag="div">
  <template #combined="{ isPending, isDelayOver, error }">
    <div>isPending: {{ isPending }}</div>
    <div>isDelayOver: {{ isDelayOver }}</div>
    <div>error: {{ error }}</div>
  </template>
</Promised>
```

From the code I now see, that you have an assertion:

```typescript
    assert(
      (Array.isArray(node) && node.length === 1) || node,
      'Provided "combined" scoped-slot cannot be empty and must contain one single children'
    )
```

So either the `|| node` has to be removed and (if I have not just overlooked it) this information must be added to the documentation; or the possibility to have multiple child nodes in the combined slot should be added.

**Comment by posva** [comment]
hey can you put that in a jsfiddle so I can test? thanks!

**Comment by posva** [comment]
got time to look it, yeah, this makes sense to be supported now
