### ISSUE TITLE
Transitions not working

### ISSUE THREAD

**Issue by plehnen** [posva/vue-promised#23]
Hi, I would like to combine vue-promised with transitions, so that the loading indicator is propery faded in and faded out, as well as the final result.

```
<transition name="fade" mode="out-in" appear>
  <Promised :promise="promise">
    <template #pending>
      <p>Loading...</p>
    </template>
     <article>
      Content ...
    </article>
  </Promised>
</transition>
```

**What is expected:**
After the promise is resolved, "Loading..." should fade out and the "Content" should fade in.

**What is actually happening:**
Only "Loading..." is faded in, and will change to the "Content" without transition.

**Comment by posva** [comment]
I will take a look, for the moment you can use the combined slot instead and use the transition component inside it

**Comment by posva** [comment]
If you are using transitions, you will have to use the combined slot for the moment. I'm going to open another issue for the feature request but the transition should be the Promised component itself which is not possible right now because it doesn't pass down props

```vue
      <Promised
        v-slot:combined="{ isPending, isDelayOver, data ,error }"
        :promise="promise"
      >
        <div>
          <transition name="fade" mode="out-in">
            <p v-if="error" key="error">Error: {{ error.message }}</p>
			<p v-else-if="!isDelayOver" key="delay"></p>
            <p v-else-if="isPending">Loading</p>
            <p v-else key="data">{{ data }}</p>
          </transition>
        </div>
      </Promised>
```
