### ISSUE TITLE
Doesn't work with Vue@2

### ISSUE THREAD

**Issue by VladStepanov** [posva/vue-promised#233]
### Reproduction

https://codesandbox.io/s/loving-lichterman-6lb9t?file=/src/main.js

### Steps to reproduce the behavior

Just install it with Vue@2

### Expected behavior

Works fine

### Actual behavior

We have warnings in console and app doesn't start
![image](https://user-images.githubusercontent.com/49880862/99875295-0d995080-2bf7-11eb-945e-7e1e8dbc146d.png)

### Additional information

With vue-promised@1 all works fine. Looks like backward compatibility is broken

**Comment by posva** [comment]
Thanks, I found out the problem. You will have another warning about a missing export but the lib should work with Vue 2 now!
It might require you to reinstall vue-promised to make sure it triggers the postinstall hooks
Note, v2 requires @vue/composition-api to work (I will add that to the readme)

**Comment by SeregPie** [comment]
Hi.

There is still an error by webpack.

```
"export 'warn' was not found in 'vue-demi'
```
