### ISSUE TITLE
README clarifications

### ISSUE THREAD

**Issue by babelfish** [posva/vue-promised#299]
I had a couple issues when I first tried to use this that I think could be avoided with some clarified wording in the docs.

The section on the combined slot says:
> You can also provide a single combined slot that will receive a context with all relevant information.

Which isn't necessarily clear that you can _literally_ only provide a single combined slot and any others would be ignored. I initially tried to use it alongside the pending slot for debugging purposes. Which brings me to...

`pendingDelay` is only explained when you get to the API reference section at the bottom. I was confused why the content of the pending slot never appeared even though I could switch to the combined slot and watch the values change. The majority of users aren't going to read the entire README before trying to use something. It would be helpful to mention this in the section that explains how to use the component.

It would also be helpful to note that you need to install @vue/composition-api for this to work with Vue 2.

**Comment by posva** [comment]
Thanks for the proposals, I included the recommendations in the readme.

PS: This is the kind of things where a PR is more appreciated than an issue 🙂
