### ISSUE TITLE
Empty state template when promise returns an empty result 

### ISSUE THREAD

**Issue by natsuo** [posva/vue-promised#301]
When a new user starts using your service or product, they are often faced with an empty state. They haven't created a new task, product, customer or whatever else your product handles. Or maybe they've just hit that elusive inbox zero point.

A well designed empty state can help your user along, letting them know they can add a task by clicking a button.

The project's code would, in my opinion anyway, look a lot nicer if the empty state code was handled right inside the Promised component. That way you wouldn't need to wrap the contents of the default slot in a `v-if`.

```vue
<Promised :promise="notesPromise">
    <template #pending>
      <p>Loading...</p>
    </template>
    <template #default="data">
      <ul>
        <li v-for="note in data">{{ note.title }}</li>
      </ul>
    </template>
    <template #emptystate>
      <h1>Add your first note</h1>
      <p>Relax and write something beautiful</p>
      <button/> 
    </template>
    <template #rejected="error">
      <p>Error: {{ error.message }}</p>
    </template>
  </Promised>
```

The template should be visible when the resource has been fetched, but returned no data. The error state takes priority over the empty state. If the empty state template isn't being used, it should instead return the default template.

**Comment by posva** [comment]
I agree but in practice, I've seen APIs return all kind of objects for empty states, so I don't think this is feasible because an empty state means different things for people. It should be handled with a `v-if` as you suggested, being able to use any condition you want inside of the `default` slot:

```vue
<Promised :promise="notesPromise">
    <template #pending>
      <p>Loading...</p>
    </template>
    <template #default="data">
      <ul v-if="Array.isArray(data)">
        <li v-for="note in data">{{ note.title }}</li>
      </ul>
      <div v-else>
        <h1>Add your first note</h1>
        <p>Relax and write something beautiful</p>
        <button/> 
      </div>
    </template>
    <template #rejected="error">
      <p>Error: {{ error.message }}</p>
    </template>
  </Promised>
```
