### ISSUE TITLE
Support for Vue 2.7, no longer require @vue/composition-api

### ISSUE THREAD

**Issue by mikerockett** [posva/vue-promised#394]
### What problem is this solving

Currently, Vue Promised supports Vue 2.6.x or Vue 3. When using 2.6.x, @vue/composition-api is a required dependency, but this is no longer supported in Vue 2.7. Removal of the dependency, as noted by the upgrade guide, causes a warning to be issued in Vue CLI 5:

> export 'warn' (imported as 'warn') was not found in 'vue-demi' (possible exports: EffectScope, Vue, Vue2, computed, customRef, defineComponent, del, effectScope, getCurrentInstance, getCurrentScope, h, inject, install, isProxy, isReactive, isReadonly, isRef, isShallow, isVue2, isVue3, markRaw, mergeDefaults, nextTick, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onScopeDispose, onServerPrefetch, onUnmounted, onUpdated, provide, reactive, readonly, ref, set, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, useAttrs, useCssModule, useCssVars, useSlots, version, watch, watchEffect, watchPostEffect, watchSyncEffect)

I haven't done much digging here, but I assume `warn` is specific to vue-demi.

### Proposed solution

Add support for Vue 2.7 by removing the need for @vue/composition-api.

(Note: I have opened this as a feature request instead of a bug, as it asks for changes targetting a new version of Vue, and not one that is currently supported.)

**Comment by posva** [comment]
vue 2.7 is already supported through vue-demi but the warn should be changed to a regular console.warn. PR welcome!

**Comment by h0rn3z0r** [comment]
Did you have a chance to test if vue-promised is **fully** functional with Vue 2.7?

After updating from 2.6.14, I am getting these errors on promise rejection:

![promised](https://user-images.githubusercontent.com/8987403/225073518-d3df3165-ccff-4656-9cbf-92029284a2f8.png)
