### ISSUE TITLE
throw error on chrome devtool when use vue-promised

### ISSUE THREAD

**Issue by yuweiqi666** [posva/vue-promised#425]
### Reproduction

when promise return rejected result
chrome will normal display rejected message but chrome devtool will throw error message

### Steps to reproduce the behavior

1. let promise return rejected result
2. wait promise change rejected state
3. chrome devtool throw error message

### Expected behavior

chrome devtool should not throw error message

### Actual behavior

chrome devtool throw error message

### Additional information

vue version：vue 2.6.14

![图片](https://user-images.githubusercontent.com/62794603/229703724-912588b3-ab87-4c9d-a918-1062f946e2c8.png)

![图片](https://user-images.githubusercontent.com/62794603/229704091-f1e9a0c8-b5b5-4356-ac42-84b4e3e9400f.png)

**Comment by posva** [comment]
When putting code, paste the code not a screenshot, otherwise it's very annoying to test 😄
