### ISSUE TITLE
is useAsyncState from vueUse recommended instead of this library?

### ISSUE THREAD

**Issue by husayt** [posva/vue-promised#450]
This is a question, as i see useAsyncState from `vueUse` is solving the same problem. I wonder if '[vue-promised](https://github.com/posva/vue-promised)' has any advantages or it is better to use useAsyncState?

Thanks.

**Comment by posva** [comment]
It's just been around for way longer, but both should work. You can always check the source code and even copy paste it into your project and adapt it
