### ISSUE TITLE
Lazy or non-eager promises

### ISSUE THREAD

**Issue by tbontb-iaq** [posva/vue-promised#454]
### What problem is this solving

Sometimes we don't need to start executing, such as request, immediately.

### Proposed solution

Add a `lazy` or `eager` option to props and add a new slot called `init`, providing a `start` function to start the promise.

### Describe alternatives you've considered

Write a component to wrap this component and provide this feature.

Maybe this is not a good idea, because Promise only has `pending`, `fulfilled`, and `rejected` states, but no `init` or `not-started` state.

**Comment by posva** [comment]
The promise prop can be null. Set it to a promise when it is created and you will have what you want. See https://github.com/posva/vue-promised/issues/11
