### ISSUE TITLE
Pass a function returning a Promise instead of a Promise

### ISSUE THREAD

**Issue by rigwild** [posva/vue-promised#67]
Hello!

Loving this lib. ❤️ 

I think it would be very useful to add the possibility to pass a function returning a Promise, instead of a simple promise. This would add the ease of use of throwing before starting a call (checking call prerequisites).

You could wrap the provided function in a new Promise like this:
```js
/**
 * Wrap a function into a Promise.
 * @param {Function} fn Function to wrap
 * @returns {Promise<any>} The function execution wrapped in a Promise
 */
const wrapFn = fn => new Promise((resolve, reject) => fn()
      .then(resolve)
      .catch(reject))
```

Adding this would make the following possible:
```js
myFunction() {
  if (!this.falsyData) throw new Error('Your data is falsy')
  return apiCall()
}

this.promise = myFunction
```
The thrown error would then be passed to the `<Promised>` component `rejected` slot.

Have a nice day!

**Comment by posva** [comment]
Hi, I' glad you are liking it! I don't understand why this would be better than doing

```js
myFunction() {
  if (!this.falsyData) throw new Error('Your data is falsy')
  this.promise = apiCall()
}
```

This way, you can call the function again whenever needed whereas the other version will only work once

**Comment by rigwild** [comment]
When doing it like this, the thrown error wouldn't be displayed in the `<Promised>` component. You would then need to catch it and code another error handler, when `vue-promised` has already everything needed 😞

**Comment by posva** [comment]
Ah, I see. I didn't know you wanted to catch that error as well. In that case, I would return a promise rejection with Promise.reject or make the function async but I still don't see the advantage against:

```js
this.promise = this.myFunction()
```

The other problem is still inherent to allowing a function since it will only get called once

**Comment by rigwild** [comment]
You are right. I think I got conflicted in my mind. This is probably not necessary after all 🙄

Thanks and have a nice day!
